const DATA={
ward:[
{id:"leni",name:"Ald. Leni Manaa-Hoppenworth",role:"Alderwoman — 48th Ward",addr:"1129 W Bryn Mawr Ave",phone:"773-784-5277",email:"leni@the48thward.org",web:"https://the48thward.org",desc:"Elected alderwoman serving the 48th Ward since 2023. Covers Edgewater, Uptown, and Andersonville neighborhoods."},
{id:"nicole",name:"Nicole Granacki",role:"Chief of Staff",phone:"773-352-1554",email:"nicole@the48thward.org",desc:"Oversees ward office operations, constituent services, and staff management."},
{id:"angel",name:"Angel Rubi Navarijo",role:"Dir. of Neighborhood Services",phone:"773-352-1553",email:"angel@the48thward.org",desc:"Handles neighborhood complaints, zoning issues, and business corridor support."},
{id:"agnes",name:"Agnes Chan",role:"Dir. of Planning & Infrastructure",email:"agnes@the48thward.org",desc:"Manages infrastructure projects, development review, and capital improvements."},
{id:"audrey",name:"Audrey Champelli",role:"Communications Manager",email:"audrey@the48thward.org",desc:"Manages newsletters, social media, press, and the Newsies volunteer program."},
{id:"conor",name:"Conor Hart",role:"Volunteer Coordinator",email:"conor@the48thward.org",desc:"Coordinates ward volunteers, community events, and outreach programs."},
],
social:[
{id:"fb-official",name:"48th Ward (Official)",platform:"Facebook",url:"https://www.facebook.com/the48thward/",desc:"Official Facebook page of the 48th Ward office."},
{id:"ig-official",name:"48th Ward Instagram",platform:"Instagram",url:"https://www.instagram.com/the48thward/",desc:"Official Instagram for ward news and photos."},
{id:"fb-edgewater",name:"Edgewater Neighbors",platform:"Facebook Group",url:"https://www.facebook.com/share/g/18AJvP8RQa/",desc:"Active discussion group for Edgewater residents."},
{id:"fb-edgenews",name:"Edgewater Neighborhood News",platform:"Facebook Group",url:"https://www.facebook.com/share/g/17FcUxYP8r/",desc:"News and updates for the Edgewater neighborhood."},
{id:"fb-uptown",name:"Uptown Community Connections",platform:"Facebook Group",url:"https://www.facebook.com/share/g/1Byp7Lo8nb/",desc:"Community connections for Uptown residents."},
{id:"fb-andersonville",name:"Andersonville News & Discourse",platform:"Facebook Group",url:"https://www.facebook.com/share/g/1CNUT2jjvq/",desc:"Neighborhood news and discussion for Andersonville."},
],
city:[
{id:"311",name:"311 City Services",desc:"Non-emergency city services hotline — report potholes, graffiti, streetlights out, garbage issues, tree trimming, rodents, and more.",phone:"311",web:"https://www.chicago.gov/city/en/depts/311.html"},
{id:"cpd",name:"Chicago Police Department",desc:"20th District covers the 48th Ward. Non-emergency and community policing.",phone:"312-742-8714",web:"https://www.chicago.gov/city/en/depts/cpd.html"},
{id:"cfd",name:"Chicago Fire Department",desc:"Fire, EMS, and emergency response services.",phone:"911",web:"https://www.chicago.gov/city/en/depts/cfd.html"},
{id:"streets",name:"Streets & Sanitation",desc:"Garbage collection, recycling, street sweeping, graffiti removal, rodent baiting, and tree trimming.",phone:"312-744-5000",web:"https://www.chicago.gov/city/en/depts/streets.html"},
{id:"cdot",name:"CDOT — Transportation",desc:"Street repairs, potholes, bike lanes, traffic signals, speed bumps, and pedestrian safety.",phone:"312-744-3600",web:"https://www.chicago.gov/city/en/depts/cdot.html"},
{id:"water",name:"Water Management",desc:"Water billing, water quality testing, sewer maintenance, and flood control.",phone:"312-744-4426",web:"https://www.chicago.gov/city/en/depts/water.html"},
{id:"bldgs",name:"Buildings Department",desc:"Building permits, code violations, inspections, and zoning compliance.",phone:"312-744-3449",web:"https://www.chicago.gov/city/en/depts/bldgs.html"},
{id:"cdph",name:"Public Health",desc:"Health clinics, vaccines, food safety inspections, mental health, and substance abuse services.",phone:"312-747-9884",web:"https://www.chicago.gov/city/en/depts/cdph.html"},
{id:"cacc",name:"Animal Care & Control",desc:"Dog registration, stray animal pickup, lost pets, adoption, and bite reports.",phone:"312-747-1406",web:"https://www.chicago.gov/city/en/depts/cacc.html"},
{id:"fss",name:"Family & Support Services",desc:"Senior services, homeless outreach, workforce development, domestic violence, and youth programs.",phone:"312-743-0300",web:"https://www.chicago.gov/city/en/depts/fss.html"},
{id:"dcd",name:"Planning & Development",desc:"Zoning changes, land use, TIF districts, landmarks, and development projects.",phone:"312-744-4190",web:"https://www.chicago.gov/city/en/depts/dcd.html"},
{id:"doh",name:"Housing",desc:"Affordable housing, rental assistance, homebuyer programs, and housing inspections.",phone:"312-742-0484",web:"https://www.chicago.gov/city/en/depts/doh.html"},
{id:"dca",name:"Cultural Affairs & Special Events",desc:"Festivals, public art, film permits, Millennium Park, and city cultural programs.",phone:"312-744-3316",web:"https://www.chicago.gov/city/en/depts/dca.html"},
{id:"env",name:"Environment",desc:"Recycling, air quality, brownfield cleanup, lead testing, and environmental complaints.",phone:"312-744-7606",web:"https://www.chicago.gov/city/en/depts/env.html"},
{id:"copa",name:"COPA — Police Accountability",desc:"Civilian oversight of police misconduct complaints and use-of-force investigations.",phone:"312-743-COPA",web:"https://www.chicago.gov/city/en/depts/copa.html"},
{id:"oem",name:"Emergency Management",desc:"NotifyChicago alerts, emergency preparedness, CERT volunteer program.",phone:"312-746-9111",web:"https://www.chicago.gov/city/en/depts/oem.html"},
{id:"bacp",name:"Business Affairs & Consumer Protection",desc:"Business licenses, consumer complaints, food establishment licenses, sidewalk cafes.",phone:"312-744-6060",web:"https://www.chicago.gov/city/en/depts/bacp.html"},
{id:"fin",name:"Finance",desc:"Parking tickets, red-light tickets, tax payments, utility billing, debt collection.",phone:"312-744-4430",web:"https://www.chicago.gov/city/en/depts/fin.html"},
{id:"cchr",name:"Human Relations",desc:"Discrimination complaints, hate crime reporting, community mediation.",phone:"312-744-4111",web:"https://www.chicago.gov/city/en/depts/cchr.html"},
{id:"mopd",name:"People with Disabilities",desc:"Home modifications, accessible services, disability ID cards, ADA compliance.",phone:"312-744-7050",web:"https://www.chicago.gov/city/en/depts/mopd.html"},
{id:"ethics",name:"Board of Ethics",desc:"Ethics complaints, lobbyist registration, financial disclosure, ethics training.",phone:"312-744-9660",web:"https://www.chicago.gov/city/en/depts/ethics.html"},
{id:"dhr",name:"Human Resources",desc:"City job opportunities, employee benefits, internships.",phone:"312-744-4190",web:"https://www.chicago.gov/city/en/depts/dhr.html"},
{id:"law",name:"Law Department",desc:"City legal services, FOIA requests, ordinance interpretation.",phone:"312-744-6900",web:"https://www.chicago.gov/city/en/depts/dol.html"},
{id:"igo",name:"Inspector General",desc:"Government waste, fraud, and corruption investigations.",phone:"312-744-3000",web:"https://www.chicago.gov/city/en/depts/igo.html"},
{id:"obm",name:"Budget & Management",desc:"City budget, financial planning, performance management.",phone:"312-744-3300",web:"https://www.chicago.gov/city/en/depts/obm.html"},
],
agencies:[
{id:"cpd-parks",name:"Chicago Park District",desc:"Parks, beaches, pools, sports leagues, after-school programs, senior programs, and nature centers.",phone:"312-742-PLAY",web:"https://www.chicagoparkdistrict.com"},
{id:"cta",name:"CTA — Transit Authority",desc:"Bus and train routes, Ventra cards, service alerts, accessibility, and reduced fare programs.",phone:"888-968-7282",web:"https://www.transitchicago.com"},
{id:"cps",name:"Chicago Public Schools",desc:"K-12 public education, GoCPS enrollment, special education, after-school programs.",phone:"773-553-1000",web:"https://www.cps.edu"},
{id:"ccc",name:"City Colleges of Chicago",desc:"Community colleges, workforce training, GED programs. Truman College serves the 48th Ward.",phone:"773-COLLEGE",web:"https://www.ccc.edu"},
{id:"cha",name:"Chicago Housing Authority",desc:"Public housing, housing choice vouchers (Section 8), waitlist applications.",phone:"312-742-8500",web:"https://www.thecha.org"},
{id:"cpl",name:"Chicago Public Library",desc:"Library cards, programs, computer access, meeting rooms. Edgewater Branch at 6000 N Broadway.",phone:"312-747-4300",web:"https://www.chipublib.org"},
{id:"metra",name:"Metra Commuter Rail",desc:"Commuter train service to suburbs and downtown.",phone:"312-322-6777",web:"https://metra.com"},
{id:"pace",name:"Pace Suburban Bus",desc:"Suburban and paratransit bus services connecting with CTA.",phone:"847-364-7223",web:"https://pacebus.com"},
],
elected:[
{id:"mayor",name:"Mayor Brandon Johnson",role:"Mayor of Chicago",phone:"312-744-3300",web:"https://www.chicago.gov/city/en/depts/mayor.html",desc:"Executive head of the City of Chicago municipal government."},
{id:"clerk",name:"Anna Valencia",role:"City Clerk",phone:"312-744-6861",web:"https://www.chicityclerk.com",desc:"Vehicle stickers, city ID, birth/death/marriage certificates, municipal code."},
{id:"treasurer",name:"Melissa Conyears-Ervin",role:"City Treasurer",phone:"312-744-3356",web:"https://www.chicagocitytreasurer.com",desc:"City investments, banking relationships, financial literacy programs."},
{id:"durbin",name:"Sen. Dick Durbin",role:"U.S. Senator — Illinois",phone:"312-353-4952",web:"https://www.durbin.senate.gov",desc:"Senior U.S. Senator from Illinois. Chicago office: 230 S Dearborn St, Suite 3892."},
{id:"duckworth",name:"Sen. Tammy Duckworth",role:"U.S. Senator — Illinois",phone:"312-886-3506",web:"https://www.duckworth.senate.gov",desc:"Junior U.S. Senator from Illinois. Iraq War veteran and disability rights advocate."},
{id:"quigley",name:"Rep. Mike Quigley",role:"U.S. Representative — IL-5",phone:"773-267-5926",web:"https://quigley.house.gov",desc:"Represents Illinois' 5th Congressional District including the 48th Ward."},
{id:"pritzker",name:"Gov. JB Pritzker",role:"Governor of Illinois",phone:"217-782-0244",web:"https://www.illinois.gov/government/governor",desc:"Governor of the State of Illinois."},
{id:"elections",name:"Cook County Board of Elections",role:"Voter Registration & Polling",phone:"312-603-0906",web:"https://www.chicagoelections.com",desc:"Voter registration, polling place lookup, election results, early voting locations."},
{id:"assessor",name:"Cook County Assessor",role:"Property Tax Assessment",phone:"312-443-7550",web:"https://www.cookcountyassessor.com",desc:"Property tax assessment, appeals, exemptions (homeowner, senior, senior freeze)."},
],
community:[
{id:"edgewater-lib",name:"Edgewater Branch Library",desc:"Public library with programs, wifi, meeting rooms, and children's activities.",addr:"6000 N Broadway",phone:"312-742-1945",web:"https://www.chipublib.org"},
{id:"berger",name:"Berger Park Cultural Center",desc:"Events, classes, art exhibits, rentals, and community programming in a lakefront setting.",addr:"6205 N Sheridan Rd",phone:"312-742-7871"},
{id:"swedish-museum",name:"Swedish American Museum",desc:"Andersonville landmark celebrating Swedish-American heritage with exhibits, events, and a children's museum.",addr:"5211 N Clark St",phone:"773-728-8111",web:"https://www.swedishamericanmuseum.org"},
{id:"loyola",name:"Loyola University Chicago",desc:"Private Jesuit university. Lake Shore Campus in Rogers Park with student civic engagement programs.",addr:"1032 W Sheridan Rd",phone:"773-274-3000",web:"https://www.luc.edu"},
{id:"hopleaf",name:"Hopleaf Bar",desc:"Iconic Andersonville Belgian beer bar and neighborhood gathering spot since 1992.",addr:"5148 N Clark St",web:"https://www.hopleafbar.com"},
{id:"edgewater-hist",name:"Edgewater Historical Society",desc:"Preserving and sharing the history of the Edgewater neighborhood.",web:"https://www.edgewaterhistory.org"},
{id:"andersonville-chamber",name:"Andersonville Chamber of Commerce",desc:"Business association supporting local shops and restaurants along Clark Street.",addr:"5153 N Clark St",web:"https://www.andersonville.org"},
],
schools:[
{id:"goudy",name:"Goudy Technology Academy",desc:"CPS Elementary, K-8. Technology-focused curriculum.",addr:"5120 N Winthrop Ave",phone:"773-534-2590",web:"https://www.cps.edu"},
{id:"swift",name:"Swift Elementary School",desc:"CPS Elementary, K-8. Strong community involvement.",addr:"5900 N Winthrop Ave",phone:"773-534-2525",web:"https://www.cps.edu"},
{id:"peirce",name:"Peirce International School",desc:"CPS Elementary with International Baccalaureate program.",addr:"1423 W Bryn Mawr Ave",phone:"773-534-2410",web:"https://www.cps.edu"},
{id:"senn",name:"Senn High School",desc:"CPS High School, 9-12. International Baccalaureate and fine arts programs.",addr:"5900 N Glenwood Ave",phone:"773-534-2365",web:"https://www.cps.edu"},
{id:"sullivan",name:"Sullivan High School",desc:"CPS High School, 9-12. Diverse student body with college prep focus.",addr:"6631 N Bosworth Ave",phone:"773-534-2000",web:"https://www.cps.edu"},
{id:"uplift",name:"Uplift Community High School",desc:"CPS High School, 9-12. Small school model with personalized learning.",addr:"900 W Wilson Ave",phone:"773-534-9100",web:"https://www.cps.edu"},
{id:"truman",name:"Truman College",desc:"City Colleges of Chicago community college. Degrees, certificates, ESL, GED, and workforce training.",addr:"1145 W Wilson Ave",phone:"773-907-4000",web:"https://www.trumancollege.edu"},
{id:"loyola-u",name:"Loyola University Chicago",desc:"Private Jesuit university. Lake Shore Campus.",addr:"1032 W Sheridan Rd",phone:"773-274-3000",web:"https://www.luc.edu"},
{id:"brennemann",name:"Brennemann Elementary",desc:"CPS Elementary, Pre-K through 8.",addr:"4727 N Ashland Ave",phone:"773-534-5425",web:"https://www.cps.edu"},
{id:"hayt",name:"Hayt Elementary School",desc:"CPS Elementary, Pre-K through 8. Regional gifted center.",addr:"1518 W Granville Ave",phone:"773-534-2485",web:"https://www.cps.edu"},
],
religious:[
{id:"emanuel",name:"Emanuel Congregation",desc:"Reform Jewish synagogue founded in 1880. Active community programming and social justice advocacy.",addr:"5959 N Sheridan Rd",phone:"773-561-5173",web:"https://www.emanuelcong.org"},
{id:"st-ita",name:"St. Ita Church",desc:"Roman Catholic parish established in 1900. Beautiful Gothic Revival architecture.",addr:"1220 W Catalpa Ave",phone:"773-561-5343"},
{id:"edgewater-pres",name:"Edgewater Presbyterian Church",desc:"Presbyterian church hosting community meetings and neighborhood events.",addr:"1020 W Bryn Mawr Ave",phone:"773-561-4748"},
{id:"st-gregory",name:"St. Gregory the Great Church",desc:"Episcopal parish with arts ministry, concerts, and community outreach.",addr:"1609 W Gregory St",phone:"773-561-3546",web:"https://www.stgregoryschicago.org"},
{id:"ebenezer",name:"Ebenezer Lutheran Church",desc:"ELCA Lutheran church in Andersonville with strong community service programs.",addr:"1650 W Foster Ave",phone:"773-561-8496",web:"https://www.ebenezerchurch.org"},
{id:"buddhist-temple",name:"Buddhist Temple of Chicago",desc:"Jodo Shinshu Buddhist temple offering meditation, dharma talks, and cultural events.",addr:"1151 W Leland Ave",phone:"773-334-4661",web:"https://www.budtempchi.org"},
{id:"icc",name:"Islamic Community Center",desc:"Mosque and community center serving Muslim residents in Uptown.",addr:"4380 N Elston Ave",phone:"773-725-9047"},
{id:"ravenswood-fellowship",name:"Ravenswood Fellowship UMC",desc:"United Methodist church with food pantry and community outreach.",addr:"4511 N Hermitage Ave",phone:"773-561-2610"},
],
businesses:[
{id:"hopleaf-biz",name:"Hopleaf Bar",desc:"Iconic Belgian beer bar. 60+ draft beers, mussels, and a neighborhood institution since 1992.",addr:"5148 N Clark St",web:"https://www.hopleafbar.com",cat:"Restaurant & Bar"},
{id:"wcf",name:"Women & Children First",desc:"Feminist bookstore since 1979. Books, events, author readings, and community space.",addr:"5233 N Clark St",phone:"773-769-9299",web:"https://www.womenandchildrenfirst.com",cat:"Bookstore"},
{id:"marianos",name:"Mariano's Fresh Market",desc:"Full-service grocery store with prepared foods, bakery, and pharmacy.",addr:"5201 N Sheridan Rd",phone:"773-275-0500",cat:"Grocery"},
{id:"jewel",name:"Jewel-Osco",desc:"Grocery store with pharmacy and deli.",addr:"5343 N Broadway",phone:"773-275-4141",cat:"Grocery"},
{id:"big-jones",name:"Big Jones",desc:"Upscale Southern cuisine. Award-winning chef-driven restaurant in Andersonville.",addr:"5347 N Clark St",web:"https://www.bigjoneschicago.com",cat:"Restaurant"},
{id:"uncommon",name:"Uncommon Ground",desc:"Farm-to-table restaurant with certified organic rooftop farm. Two locations.",addr:"1401 W Devon Ave",web:"https://www.uncommonground.com",cat:"Restaurant"},
{id:"svea",name:"Svea Restaurant",desc:"Classic Swedish diner. Pancakes, meatballs, and Andersonville heritage since 1929.",addr:"5236 N Clark St",phone:"773-275-7738",cat:"Restaurant"},
{id:"simons",name:"Simon's Tavern",desc:"Historic bar since 1934. Glögg in winter, neighborhood dive vibes year-round.",addr:"5210 N Clark St",phone:"773-878-0894",cat:"Bar"},
{id:"spoke-bird",name:"The Spoke & Bird",desc:"Modern cafe and bar in Edgewater. Craft cocktails, brunch, and neighborhood gathering spot.",addr:"5714 N Broadway",cat:"Restaurant & Bar"},
{id:"replay",name:"Replay Andersonville",desc:"Arcade bar with retro games, pinball, craft beer, and late-night fun.",addr:"5358 N Clark St",web:"https://www.replaychi.com",cat:"Bar & Entertainment"},
{id:"georges",name:"George's Ice Cream & Sweets",desc:"Neighborhood ice cream shop in Edgewater. Homemade flavors and treats.",addr:"5306 N Sheridan Rd",cat:"Ice Cream"},
{id:"early-bed",name:"Early to Bed",desc:"Boutique retail shop in Andersonville.",addr:"5044 N Clark St",web:"https://www.early2bed.com",cat:"Retail"},
{id:"reza",name:"Reza's Restaurant",desc:"Persian and Middle Eastern cuisine. Large portions and warm atmosphere.",addr:"5255 N Clark St",phone:"773-561-1898",cat:"Restaurant"},
{id:"ann-sather",name:"Ann Sather",desc:"Swedish-American diner. Famous cinnamon rolls and Swedish pancakes since 1945.",addr:"5207 N Clark St",phone:"773-271-6677",web:"https://www.annsather.com",cat:"Restaurant"},
{id:"middle-east-bakery",name:"Middle East Bakery & Grocery",desc:"Authentic Middle Eastern bakery, groceries, and prepared foods since 1980.",addr:"1512 W Foster Ave",phone:"773-561-2224",cat:"Bakery & Grocery"},
{id:"edgewater-produce",name:"Edgewater Produce",desc:"Family-owned fruit and vegetable market with competitive prices.",addr:"5515 N Broadway",cat:"Grocery"},
{id:"hamburger-mary",name:"Hamburger Mary's",desc:"LGBTQ+ friendly burger bar with drag shows and entertainment in Andersonville.",addr:"5400 N Clark St",web:"https://www.hamburgermarys.com/chicago",cat:"Restaurant & Entertainment"},
{id:"la-fournette",name:"La Fournette",desc:"French artisan bakery with breads, pastries, and cafe. Andersonville gem.",addr:"1547 W Foster Ave",phone:"773-907-8261",web:"https://www.lafournette.com",cat:"Bakery & Cafe"},
{id:"lady-gregory",name:"Lady Gregory's",desc:"Irish pub with craft beers, weekend brunch, and a cozy Andersonville atmosphere.",addr:"5260 N Clark St",phone:"773-271-5050",cat:"Restaurant & Bar"},
{id:"first-slice",name:"First Slice Pie Cafe",desc:"Nonprofit cafe. Pies, quiche, and sandwiches. Proceeds fund meals for food-insecure neighbors.",addr:"5357 N Ashland Ave",web:"https://www.firstslice.org",cat:"Cafe (Nonprofit)"},
{id:"rattleback",name:"Rattleback Records",desc:"Independent record store. New and used vinyl, local music events.",addr:"5405 N Clark St",cat:"Record Store"},
{id:"alamo-shoes",name:"Alamo Shoes",desc:"Family-owned shoe store since 1919. Wide selection, personalized fitting.",addr:"5321 N Clark St",phone:"773-334-6100",web:"https://www.alamoshoes.com",cat:"Retail — Shoes"},
{id:"foursided",name:"Foursided",desc:"Custom framing, vintage goods, greeting cards, and art prints.",addr:"5061 N Clark St",phone:"773-506-8300",web:"https://www.foursided.com",cat:"Art & Framing"},
{id:"oils-ometer",name:"Oils & Ometer",desc:"Specialty olive oil and balsamic vinegar tasting shop.",addr:"5266 N Clark St",cat:"Specialty Food"},
{id:"edgewater-medical",name:"Edgewater Medical Center (site)",desc:"Former hospital site under redevelopment discussion.",addr:"5700 N Ashland Ave",cat:"Development Site"},
{id:"presence-health",name:"Presence St. Francis Hospital",desc:"Full-service hospital near the ward. Emergency, surgery, and outpatient care.",addr:"355 Ridge Ave, Evanston",phone:"847-316-4000",web:"https://www.amitahealth.org",cat:"Healthcare"},
],
programs:[
{id:"newsies",name:"Newsies Program",desc:"Volunteer to distribute weekly information flyers to buildings across the ward. Great way to meet neighbors and stay informed."},
{id:"digital-newsies",name:"Digital Newsies",desc:"Share ward content on social media and in neighborhood Facebook groups. Help amplify community news."},
{id:"pb",name:"Participatory Budgeting",desc:"Annual resident-driven voting on how to spend ward infrastructure funds. Propose and vote on projects."},
{id:"newsletter",name:"Newsletter Signup",desc:"Weekly email newsletter with ward meetings, events, construction updates, and community news.",web:"https://mailchi.mp/the48thward/newsletter-signup"},
{id:"invite-ald",name:"Invite the Alderwoman",desc:"Request a town hall or presentation at your building, condo association, or community group.",web:"https://the48thward.org/invite-the-alderwoman"},
{id:"beat",name:"Beat Meetings",desc:"Monthly police-community meetings where residents can voice safety concerns and hear crime updates."},
{id:"town-halls",name:"Town Halls",desc:"Twice-yearly community town halls plus periodic infrastructure town halls on major projects."},
{id:"shred",name:"Shred & Recycling Events",desc:"Free document shredding and electronics recycling events at 5853 N Broadway. Periodic throughout the year."},
],
actions:[
{name:"Report a Pothole",url:"https://www.chicago.gov/city/en/depts/cdot/provdrs/street/svcs/report_a_pot_holeinstreet.html",icon:"🛣️"},
{name:"Report Graffiti",url:"https://www.chicago.gov/city/en/depts/streets/provdrs/graffiti_blasters/svcs/graffiti_removal.html",icon:"🎨"},
{name:"Request Garbage Cart",url:"https://www.chicago.gov/city/en/depts/streets/provdrs/rodent/svcs/garbage_cart_distribution.html",icon:"🗑️"},
{name:"Abandoned Vehicle",url:"https://www.chicago.gov/city/en/depts/streets/provdrs/traffic/svcs/abandoned_vehicles.html",icon:"🚗"},
{name:"Street Light Out",url:"https://www.chicago.gov/city/en/depts/cdot/provdrs/traffic_signals_andstreetlights/svcs/bldgviolstatus.html",icon:"💡"},
{name:"Pay Parking Ticket",url:"https://www.chicago.gov/city/en/depts/fin/provdrs/parking_and_redlightcitationadministration/svcs/pay_parking_and_red-lightticketson-line.html",icon:"🎫"},
{name:"Pay Utility Bill",url:"https://www.chicago.gov/city/en/depts/fin/provdrs/utility_billing/svcs/utility-bill.html",icon:"💧"},
{name:"Register Dog",url:"https://www.chicago.gov/city/en/depts/cacc/provdrs/care/svcs/dog_registration.html",icon:"🐕"},
{name:"NotifyChicago",url:"https://www.chicago.gov/city/en/depts/oem/provdrs/alertchicago/svcs/notifychicago.html",icon:"🔔"},
{name:"Construction Map",url:"https://chistreetwork.chicago.gov/map",icon:"🗺️"},
{name:"Voter Registration",url:"https://www.chicagoelections.com",icon:"🗳️"},
{name:"ICash Funds",url:"https://icash.illinoistreasurer.gov",icon:"💰"},
{name:"Tree Trim Request",url:"https://www.chicago.gov/city/en/depts/streets/provdrs/forestry/svcs/tree_trimming.html",icon:"🌳"},
{name:"Rodent Complaint",url:"https://www.chicago.gov/city/en/depts/streets/provdrs/rodent/svcs/rodent_baiting.html",icon:"🐀"},
{name:"Building Violation",url:"https://www.chicago.gov/city/en/depts/bldgs/provdrs/inspect/svcs/building_violationsonline.html",icon:"🏗️"},
{name:"Food Inspection",url:"https://www.chicago.gov/city/en/depts/cdph/provdrs/food_safety.html",icon:"🍽️"},
]
};
// Helper: find item by id across all categories
function findItem(id){
  for(const cat of Object.values(DATA)){
    if(!Array.isArray(cat))continue;
    const item=cat.find(i=>i.id===id);
    if(item)return item;
  }
  return null;
}
// Helper: get category label for an item
function getCatForItem(id){
  const cats={ward:'Ward Office',social:'Social',city:'City Dept',agencies:'Agency',elected:'Official',community:'Community',schools:'School',religious:'Worship',businesses:'Business',programs:'Program'};
  for(const[key,arr] of Object.entries(DATA)){
    if(!Array.isArray(arr))continue;
    if(arr.find(i=>i.id===id))return {key,label:cats[key]||key};
  }
  return {key:'other',label:'Resource'};
}
