const DATA = {
  ward: [
    {name:"Ald. Leni Manaa-Hoppenworth",role:"Alderwoman",addr:"1129 W Bryn Mawr Ave",phone:"773-784-5277",email:"leni@the48thward.org",web:"https://the48thward.org"},
    {name:"Nicole Granacki",role:"Chief of Staff",phone:"773-352-1554",email:"nicole@the48thward.org"},
    {name:"Angel Rubi Navarijo",role:"Dir. of Neighborhood Services",phone:"773-352-1553",email:"angel@the48thward.org"},
    {name:"Agnes Chan",role:"Dir. of Planning & Infrastructure",email:"agnes@the48thward.org"},
    {name:"Audrey Champelli",role:"Communications Manager",email:"audrey@the48thward.org"},
    {name:"Conor Hart",role:"Volunteer Coordinator",email:"conor@the48thward.org"},
  ],
  social: [
    {name:"48th Ward (Official)",platform:"Facebook",url:"https://www.facebook.com/the48thward/"},
    {name:"48th Ward Instagram",platform:"Instagram",url:"https://www.instagram.com/the48thward/"},
    {name:"Edgewater Neighbors",platform:"Facebook Group",url:"https://www.facebook.com/share/g/18AJvP8RQa/"},
    {name:"Edgewater Neighborhood News",platform:"Facebook Group",url:"https://www.facebook.com/share/g/17FcUxYP8r/"},
    {name:"Uptown Community Connections",platform:"Facebook Group",url:"https://www.facebook.com/share/g/1Byp7Lo8nb/"},
    {name:"Andersonville News & Discourse",platform:"Facebook Group",url:"https://www.facebook.com/share/g/1CNUT2jjvq/"},
  ],
  city: [
    {name:"311 City Services",desc:"Non-emergency: potholes, graffiti, streetlights, garbage",phone:"311",web:"https://www.chicago.gov/city/en/depts/311.html"},
    {name:"Chicago Police — 20th District",desc:"Local police district covering the 48th Ward",phone:"312-742-8714",web:"https://www.chicago.gov/city/en/depts/cpd.html"},
    {name:"Streets & Sanitation",desc:"Garbage carts, recycling, street sweeping",phone:"312-744-5000",web:"https://www.chicago.gov/city/en/depts/streets.html"},
    {name:"CDOT Transportation",desc:"Potholes, bike lanes, traffic signals",phone:"312-744-3600",web:"https://www.chicago.gov/city/en/depts/cdot.html"},
    {name:"Water Management",desc:"Billing, water quality, flooding",phone:"312-744-4426",web:"https://www.chicago.gov/city/en/depts/water.html"},
    {name:"Buildings Department",desc:"Permits, violations, inspections",phone:"312-744-3449",web:"https://www.chicago.gov/city/en/depts/bldgs.html"},
    {name:"Public Health",desc:"Vaccines, food safety, health clinics",phone:"312-747-9884",web:"https://www.chicago.gov/city/en/depts/cdph.html"},
    {name:"Animal Care & Control",desc:"Dog registration, stray animals, lost pets",phone:"312-747-1406",web:"https://www.chicago.gov/city/en/depts/cacc.html"},
    {name:"Family & Support Services",desc:"Seniors, homeless services, workforce dev",phone:"312-743-0300",web:"https://www.chicago.gov/city/en/depts/fss.html"},
    {name:"Planning & Development",desc:"Zoning, land use, TIF districts",phone:"312-744-4190",web:"https://www.chicago.gov/city/en/depts/dcd.html"},
    {name:"Housing",desc:"Affordable housing, rentals, homebuyer assist",phone:"312-742-0484",web:"https://www.chicago.gov/city/en/depts/doh.html"},
    {name:"Cultural Affairs & Special Events",desc:"Festivals, public art, film permits",phone:"312-744-3316",web:"https://www.chicago.gov/city/en/depts/dca.html"},
    {name:"Environment",desc:"Recycling, air quality, brownfields",phone:"312-744-7606",web:"https://www.chicago.gov/city/en/depts/env.html"},
    {name:"COPA",desc:"Civilian Office of Police Accountability",phone:"312-743-COPA",web:"https://www.chicago.gov/city/en/depts/copa.html"},
    {name:"Emergency Mgmt",desc:"NotifyChicago alerts, CERT volunteers",phone:"312-746-9111",web:"https://www.chicago.gov/city/en/depts/oem.html"},
  ],
  agencies: [
    {name:"Chicago Park District",desc:"Parks, beaches, programs, facilities",phone:"312-742-PLAY",web:"https://www.chicagoparkdistrict.com"},
    {name:"CTA",desc:"Buses, trains, Ventra cards",phone:"888-968-7282",web:"https://www.transitchicago.com"},
    {name:"Chicago Public Schools",desc:"K-12 education",phone:"773-553-1000",web:"https://www.cps.edu"},
    {name:"City Colleges of Chicago",desc:"Higher education — Truman College nearby",phone:"773-COLLEGE",web:"https://www.ccc.edu"},
    {name:"Chicago Housing Authority",desc:"Housing choice vouchers, public housing",phone:"312-742-8500",web:"https://www.thecha.org"},
    {name:"Chicago Public Library",desc:"Edgewater Branch, programs, wifi",phone:"312-747-4300",web:"https://www.chipublib.org"},
  ],
  elected: [
    {name:"Mayor Brandon Johnson",role:"Mayor of Chicago",phone:"312-744-3300",web:"https://www.chicago.gov/city/en/depts/mayor.html"},
    {name:"Sen. Dick Durbin",role:"U.S. Senator",phone:"312-353-4952",web:"https://www.durbin.senate.gov"},
    {name:"Sen. Tammy Duckworth",role:"U.S. Senator",phone:"312-886-3506",web:"https://www.duckworth.senate.gov"},
    {name:"Rep. Mike Quigley",role:"U.S. Representative — IL-5",phone:"773-267-5926",web:"https://quigley.house.gov"},
    {name:"Gov. JB Pritzker",role:"Governor of Illinois",phone:"217-782-0244",web:"https://www.illinois.gov/government/governor"},
    {name:"Cook County Board of Elections",role:"Voter registration & polling",phone:"312-603-0906",web:"https://www.chicagoelections.com"},
    {name:"Cook County Assessor",role:"Property tax assessment & appeals",phone:"312-443-7550",web:"https://www.cookcountyassessor.com"},
  ],
  community: [
    {name:"Edgewater Branch Library",desc:"Programs, wifi, meeting rooms",addr:"6000 N Broadway",phone:"312-742-1945",web:"https://www.chipublib.org"},
    {name:"Berger Park Cultural Center",desc:"Events, classes, rentals",addr:"6205 N Sheridan Rd",phone:"312-742-7871"},
    {name:"Swedish American Museum",desc:"Andersonville landmark, culture & history",addr:"5211 N Clark St",phone:"773-728-8111",web:"https://www.swedishamericanmuseum.org"},
    {name:"Loyola University Chicago",desc:"University, student civic groups",addr:"1032 W Sheridan Rd",phone:"773-274-3000",web:"https://www.luc.edu"},
    {name:"Hopleaf Bar",desc:"Andersonville neighborhood institution",addr:"5148 N Clark St",web:"https://www.hopleafbar.com"},
  ],
  schools: [
    {name:"Goudy Technology Academy",desc:"CPS Elementary, K–8",addr:"5120 N Winthrop Ave",phone:"773-534-2590",web:"https://www.cps.edu"},
    {name:"Swift Elementary School",desc:"CPS Elementary, K–8",addr:"5900 N Winthrop Ave",phone:"773-534-2525",web:"https://www.cps.edu"},
    {name:"Peirce International School",desc:"CPS Elementary with IB program",addr:"1423 W Bryn Mawr Ave",phone:"773-534-2410",web:"https://www.cps.edu"},
    {name:"Senn High School",desc:"CPS High School, 9–12",addr:"5900 N Glenwood Ave",phone:"773-534-2365",web:"https://www.cps.edu"},
    {name:"Sullivan High School",desc:"CPS High School, 9–12",addr:"6631 N Bosworth Ave",phone:"773-534-2000",web:"https://www.cps.edu"},
    {name:"Uplift Community High School",desc:"CPS High School, 9–12",addr:"900 W Wilson Ave",phone:"773-534-9100",web:"https://www.cps.edu"},
    {name:"Truman College",desc:"City Colleges of Chicago, community college",addr:"1145 W Wilson Ave",phone:"773-907-4000",web:"https://www.trumancollege.edu"},
    {name:"Loyola University Chicago",desc:"Private university, Lake Shore Campus",addr:"1032 W Sheridan Rd",phone:"773-274-3000",web:"https://www.luc.edu"},
  ],
  religious: [
    {name:"Emanuel Congregation",desc:"Reform Jewish synagogue, community events",addr:"5959 N Sheridan Rd",phone:"773-561-5173",web:"https://www.emanuelcong.org"},
    {name:"St. Ita Church",desc:"Roman Catholic parish",addr:"1220 W Catalpa Ave",phone:"773-561-5343"},
    {name:"Edgewater Presbyterian Church",desc:"Presbyterian church, community meetings",addr:"1020 W Bryn Mawr Ave",phone:"773-561-4748"},
    {name:"St. Gregory the Great Church",desc:"Episcopal parish with arts ministry",addr:"1609 W Gregory St",phone:"773-561-3546",web:"https://www.stgregoryschicago.org"},
    {name:"Ebenezer Lutheran Church",desc:"ELCA Lutheran church, Andersonville",addr:"1650 W Foster Ave",phone:"773-561-8496",web:"https://www.ebenezerchurch.org"},
    {name:"Buddhist Temple of Chicago",desc:"Jodo Shinshu Buddhist temple",addr:"1151 W Leland Ave",phone:"773-334-4661",web:"https://www.budtempchi.org"},
    {name:"Islamic Community Center",desc:"Mosque & community center, Uptown",addr:"4380 N Elston Ave",phone:"773-725-9047"},
  ],
  businesses: [
    {name:"Hopleaf Bar",desc:"Belgian beer bar, Andersonville icon",addr:"5148 N Clark St",web:"https://www.hopleafbar.com"},
    {name:"Women & Children First",desc:"Feminist bookstore, Andersonville",addr:"5233 N Clark St",phone:"773-769-9299",web:"https://www.womenandchildrenfirst.com"},
    {name:"Mariano's Fresh Market",desc:"Grocery store, Edgewater",addr:"5201 N Sheridan Rd",phone:"773-275-0500"},
    {name:"Jewel-Osco Edgewater",desc:"Grocery store",addr:"5343 N Broadway",phone:"773-275-4141"},
    {name:"Big Jones",desc:"Southern cuisine, Andersonville",addr:"5347 N Clark St",web:"https://www.bigjoneschicago.com"},
    {name:"Uncommon Ground",desc:"Farm-to-table restaurant, rooftop garden",addr:"1401 W Devon Ave",web:"https://www.uncommonground.com"},
    {name:"Early to Bed",desc:"Retail, Andersonville",addr:"5044 N Clark St",web:"https://www.early2bed.com"},
    {name:"Svea Restaurant",desc:"Swedish diner, Andersonville landmark",addr:"5236 N Clark St",phone:"773-275-7738"},
    {name:"Simon's Tavern",desc:"Historic bar since 1934, Andersonville",addr:"5210 N Clark St",phone:"773-878-0894"},
    {name:"The Spoke & Bird",desc:"Cafe & bar, Edgewater",addr:"5714 N Broadway"},
    {name:"Replay Andersonville",desc:"Arcade bar, Andersonville",addr:"5358 N Clark St",web:"https://www.replaychi.com"},
    {name:"George's Ice Cream & Sweets",desc:"Ice cream shop, Edgewater",addr:"5306 N Sheridan Rd"},
  ],
  programs: [
    {name:"Newsies Program",desc:"Weekly flyer distribution in ward buildings"},
    {name:"Digital Newsies",desc:"Share ward content on social media & neighborhood Facebook groups"},
    {name:"Participatory Budgeting",desc:"Annual resident-driven voting on ward projects"},
    {name:"Newsletter Signup",desc:"Weekly newsletter from the ward office",web:"https://mailchi.mp/the48thward/newsletter-signup"},
    {name:"Invite the Alderwoman",desc:"Request a town hall presentation at your building",web:"https://the48thward.org/invite-the-alderwoman"},
    {name:"Beat Meetings",desc:"Monthly police-community meetings in the ward"},
    {name:"Town Halls",desc:"Twice yearly community town halls + infrastructure town hall"},
    {name:"Shred & Recycling Events",desc:"Document shredding and electronics recycling at 5853 N Broadway"},
  ],
  actions: [
    {name:"Report a Pothole",url:"https://www.chicago.gov/city/en/depts/cdot/provdrs/street/svcs/report_a_pot_holeinstreet.html",icon:"🛣️"},
    {name:"Report Graffiti",url:"https://www.chicago.gov/city/en/depts/streets/provdrs/graffiti_blasters/svcs/graffiti_removal.html",icon:"🎨"},
    {name:"Request Garbage Cart",url:"https://www.chicago.gov/city/en/depts/streets/provdrs/rodent/svcs/garbage_cart_distribution.html",icon:"🗑️"},
    {name:"Abandoned Vehicle",url:"https://www.chicago.gov/city/en/depts/streets/provdrs/traffic/svcs/abandoned_vehicles.html",icon:"🚗"},
    {name:"Street Light Out",url:"https://www.chicago.gov/city/en/depts/cdot/provdrs/traffic_signals_andstreetlights/svcs/bldgviolstatus.html",icon:"💡"},
    {name:"Pay Parking Ticket",url:"https://www.chicago.gov/city/en/depts/fin/provdrs/parking_and_redlightcitationadministration/svcs/pay_parking_and_red-lightticketson-line.html",icon:"🎫"},
    {name:"Pay Utility Bill",url:"https://www.chicago.gov/city/en/depts/fin/provdrs/utility_billing/svcs/utility-bill.html",icon:"💧"},
    {name:"Register Your Dog",url:"https://www.chicago.gov/city/en/depts/cacc/provdrs/care/svcs/dog_registration.html",icon:"🐕"},
    {name:"NotifyChicago Alerts",url:"https://www.chicago.gov/city/en/depts/oem/provdrs/alertchicago/svcs/notifychicago.html",icon:"🔔"},
    {name:"Construction Tracker",url:"https://chistreetwork.chicago.gov/map",icon:"🗺️"},
    {name:"Voter Registration",url:"https://www.chicagoelections.com",icon:"🗳️"},
    {name:"ICash Unclaimed Funds",url:"https://icash.illinoistreasurer.gov",icon:"💰"},
  ]
};
